<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnUploadFotoProduk</name>
   <tag></tag>
   <elementGuidId>857ad131-95c0-4749-a150-0f68a767ba8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product_images&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product_images&quot;]</value>
      <webElementGuid>5e924b6e-d852-46b4-ba47-fb6a687bde19</webElementGuid>
   </webElementProperties>
</WebElementEntity>
