<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnUploadFotoProduk</name>
   <tag></tag>
   <elementGuidId>857ad131-95c0-4749-a150-0f68a767ba8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>///input[@id=['product_image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>///input[@id=['product_image']</value>
      <webElementGuid>98ee16aa-2bcf-4a79-b5ff-82f93d3608c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
